In [1]:
!pip install numpy

    100% |████████████████████████████████| 18.1MB 2.4MB/s eta 0:00:011


In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros((1, 2), dtype=int)

array([[0, 0]])

In [7]:
np.zeros((2, 3, 4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [8]:
np.empty(5)

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [9]:
a = 1

In [10]:
np.random.rand(2, 3)

array([[0.33256883, 0.86978584, 0.02083348],
       [0.07524763, 0.30113278, 0.94947093]])

In [11]:
# [1, 10)
np.random.randint(1, 10, 20)

array([6, 4, 5, 2, 5, 5, 4, 9, 6, 4, 3, 1, 5, 4, 4, 8, 1, 2, 5, 6])

In [12]:
import random

# [1, 10)
random.randint(1, 10) # return int

4

In [13]:
arr = np.random.rand(2, 3)

In [14]:
arr.ndim

2

In [15]:
arr.shape

(2, 3)

In [16]:
arr.size

6

In [17]:
arr2 = np.random.rand(100)
arr2

array([0.93487647, 0.7293788 , 0.63822068, 0.4443302 , 0.53823003,
       0.47970093, 0.40166684, 0.04461651, 0.97387479, 0.55054419,
       0.31602759, 0.63288562, 0.8744404 , 0.47288492, 0.1962965 ,
       0.38366981, 0.08265156, 0.32546146, 0.33819204, 0.70819801,
       0.42176009, 0.41847659, 0.37734719, 0.36101764, 0.64194589,
       0.28247693, 0.11241613, 0.6637839 , 0.2356812 , 0.76069214,
       0.93372925, 0.70834871, 0.6294119 , 0.10638243, 0.76438474,
       0.25521605, 0.90041518, 0.08808377, 0.79499839, 0.03967727,
       0.95436369, 0.72804395, 0.751818  , 0.03228287, 0.17192543,
       0.00629538, 0.33683129, 0.48899512, 0.22217962, 0.55139244,
       0.92774008, 0.64635032, 0.15647273, 0.12470729, 0.53739577,
       0.04028303, 0.862724  , 0.46108103, 0.96998985, 0.39107418,
       0.60798669, 0.24681194, 0.54563547, 0.68966001, 0.68432204,
       0.73195645, 0.05570393, 0.78442785, 0.63430588, 0.16005573,
       0.22259367, 0.50332041, 0.24924502, 0.98668626, 0.20575

In [18]:
arr2.reshape(2, 50)

array([[0.93487647, 0.7293788 , 0.63822068, 0.4443302 , 0.53823003,
        0.47970093, 0.40166684, 0.04461651, 0.97387479, 0.55054419,
        0.31602759, 0.63288562, 0.8744404 , 0.47288492, 0.1962965 ,
        0.38366981, 0.08265156, 0.32546146, 0.33819204, 0.70819801,
        0.42176009, 0.41847659, 0.37734719, 0.36101764, 0.64194589,
        0.28247693, 0.11241613, 0.6637839 , 0.2356812 , 0.76069214,
        0.93372925, 0.70834871, 0.6294119 , 0.10638243, 0.76438474,
        0.25521605, 0.90041518, 0.08808377, 0.79499839, 0.03967727,
        0.95436369, 0.72804395, 0.751818  , 0.03228287, 0.17192543,
        0.00629538, 0.33683129, 0.48899512, 0.22217962, 0.55139244],
       [0.92774008, 0.64635032, 0.15647273, 0.12470729, 0.53739577,
        0.04028303, 0.862724  , 0.46108103, 0.96998985, 0.39107418,
        0.60798669, 0.24681194, 0.54563547, 0.68966001, 0.68432204,
        0.73195645, 0.05570393, 0.78442785, 0.63430588, 0.16005573,
        0.22259367, 0.50332041, 0.24924502, 0.9

In [19]:
arr2.reshape(2, 49)

ValueError: cannot reshape array of size 100 into shape (2,49)

In [20]:
arr2.reshape(2, -1)

array([[0.93487647, 0.7293788 , 0.63822068, 0.4443302 , 0.53823003,
        0.47970093, 0.40166684, 0.04461651, 0.97387479, 0.55054419,
        0.31602759, 0.63288562, 0.8744404 , 0.47288492, 0.1962965 ,
        0.38366981, 0.08265156, 0.32546146, 0.33819204, 0.70819801,
        0.42176009, 0.41847659, 0.37734719, 0.36101764, 0.64194589,
        0.28247693, 0.11241613, 0.6637839 , 0.2356812 , 0.76069214,
        0.93372925, 0.70834871, 0.6294119 , 0.10638243, 0.76438474,
        0.25521605, 0.90041518, 0.08808377, 0.79499839, 0.03967727,
        0.95436369, 0.72804395, 0.751818  , 0.03228287, 0.17192543,
        0.00629538, 0.33683129, 0.48899512, 0.22217962, 0.55139244],
       [0.92774008, 0.64635032, 0.15647273, 0.12470729, 0.53739577,
        0.04028303, 0.862724  , 0.46108103, 0.96998985, 0.39107418,
        0.60798669, 0.24681194, 0.54563547, 0.68966001, 0.68432204,
        0.73195645, 0.05570393, 0.78442785, 0.63430588, 0.16005573,
        0.22259367, 0.50332041, 0.24924502, 0.9

In [21]:
arr2.reshape(-1, 25)

array([[0.93487647, 0.7293788 , 0.63822068, 0.4443302 , 0.53823003,
        0.47970093, 0.40166684, 0.04461651, 0.97387479, 0.55054419,
        0.31602759, 0.63288562, 0.8744404 , 0.47288492, 0.1962965 ,
        0.38366981, 0.08265156, 0.32546146, 0.33819204, 0.70819801,
        0.42176009, 0.41847659, 0.37734719, 0.36101764, 0.64194589],
       [0.28247693, 0.11241613, 0.6637839 , 0.2356812 , 0.76069214,
        0.93372925, 0.70834871, 0.6294119 , 0.10638243, 0.76438474,
        0.25521605, 0.90041518, 0.08808377, 0.79499839, 0.03967727,
        0.95436369, 0.72804395, 0.751818  , 0.03228287, 0.17192543,
        0.00629538, 0.33683129, 0.48899512, 0.22217962, 0.55139244],
       [0.92774008, 0.64635032, 0.15647273, 0.12470729, 0.53739577,
        0.04028303, 0.862724  , 0.46108103, 0.96998985, 0.39107418,
        0.60798669, 0.24681194, 0.54563547, 0.68966001, 0.68432204,
        0.73195645, 0.05570393, 0.78442785, 0.63430588, 0.16005573,
        0.22259367, 0.50332041, 0.24924502, 0.

In [22]:
tmpArr = np.array([1, 2, 3, 4, 5, 6])
tmpArr

array([1, 2, 3, 4, 5, 6])

In [23]:
tmpArr.mean()

3.5

In [24]:
tmpArr.max()

6

In [25]:
tmpArr.min()

1

In [27]:
np.median(tmpArr)

3.5

In [28]:
np.percentile(tmpArr, 10)

1.5

In [29]:
np.percentile(tmpArr, 10, method="higher")

2

In [30]:
np.percentile(tmpArr, 10, method="lower")

1

In [31]:
np.percentile(tmpArr, 50, method="lower")

3

In [32]:
tmpArr.max() - tmpArr.min()

5

In [33]:
np.percentile(tmpArr, 75, method="higher") - np.percentile(tmpArr, 25, method="higher")

2

In [34]:
np.percentile(tmpArr, 75, method="higher")

5

In [35]:
5 + 2*3

11

In [36]:
tmpArr

array([1, 2, 3, 4, 5, 6])

In [37]:
tmpArr - 1

array([0, 1, 2, 3, 4, 5])

In [38]:
tmpArr * 2

array([ 2,  4,  6,  8, 10, 12])

In [39]:
np.random.normal(0, 1, 100)

array([-3.29995943e-01, -1.68510144e+00,  4.55845352e-01,  9.82040062e-01,
        5.06395017e-01, -2.56377962e-01,  1.20176347e+00,  9.84618499e-01,
        2.06983769e-01,  2.55474025e-02, -4.22152228e-01, -3.49019340e-01,
        2.01263308e+00,  2.36559886e+00,  4.25262533e-01,  6.86704121e-02,
        1.19562708e+00,  1.12244070e+00,  1.05038942e+00, -3.05551311e-01,
        5.72027234e-01, -9.97199313e-01, -5.02535446e-01, -5.38987779e-02,
        6.80803011e-01,  1.86843898e+00, -1.28417258e+00, -3.55073364e-01,
       -2.28509830e-03, -1.64352343e+00,  1.59566886e+00,  1.70008931e-01,
       -1.05158117e+00,  3.21613558e-01,  8.61538748e-02, -1.54159233e+00,
       -4.91079771e-01, -3.37424868e-01,  8.10335142e-01, -9.61175244e-01,
        6.45217933e-01, -3.66387761e-01,  9.70868273e-01,  6.04681377e-01,
        4.11350835e-01, -1.86520490e-01, -7.88267127e-01,  9.04559543e-01,
       -1.18792535e+00, -3.24831718e-01, -2.34852042e+00, -7.61801350e-01,
       -3.91412883e-01, -

In [42]:
a = np.random.normal(0, 1, 1000)
a.mean()

0.01615241986793693

In [43]:
a.std()

0.9898924727795129