In [ ]:
!pip install numpy

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [ ]:
np.zeros(10)

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
np.zeros((1, 2), dtype=int)

In [ ]:
np.zeros((2, 3, 4), dtype=int)

In [ ]:
np.empty(5)

In [ ]:
a = 1

In [ ]:
np.random.rand(2, 3)

In [ ]:
# [1, 10)
np.random.randint(1, 10, 20)

In [ ]:
import random

# [1, 10)
random.randint(1, 10) # return int

In [ ]:
arr = np.random.rand(2, 3)

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr2 = np.random.rand(100)
arr2

In [ ]:
arr2.reshape(2, 50)

In [ ]:
arr2.reshape(2, 49)

In [ ]:
arr2.reshape(2, -1)

In [ ]:
arr2.reshape(-1, 25)

In [10]:
tmpArr = np.array([1, 2, 3, 4, 5, 6])
tmpArr

array([1, 2, 3, 4, 5, 6])

In [ ]:
tmpArr.mean()

In [ ]:
tmpArr.max()

In [ ]:
tmpArr.min()

In [ ]:
np.median(tmpArr)

In [ ]:
np.percentile(tmpArr, 10)

In [ ]:
np.percentile(tmpArr, 10, method="higher")

In [ ]:
np.percentile(tmpArr, 10, method="lower")

In [ ]:
np.percentile(tmpArr, 50, method="lower")

In [ ]:
tmpArr.max() - tmpArr.min()

In [ ]:
np.percentile(tmpArr, 75, method="higher") - np.percentile(tmpArr, 25, method="higher")

In [ ]:
np.percentile(tmpArr, 75, method="higher")

In [ ]:
5 + 2*3

In [ ]:
tmpArr

In [ ]:
tmpArr - 1

In [ ]:
tmpArr * 2

In [ ]:
np.random.normal(0, 1, 100)

In [ ]:
a = np.random.normal(0, 1, 1000)
a.mean()

In [ ]:
a.std()

In [2]:
nparr = np.random.normal(0, 1, 10000)

In [3]:
pylist = list(nparr)

In [4]:
import time

time.time()

1664606837.2521029

In [5]:
st_time = time.time()

print(nparr.mean())

ed_time = time.time()
print(ed_time - st_time)

0.006291570982582874
0.0010061264038085938


In [6]:
st_time = time.time()

print(sum(pylist)/pylist.__len__())

ed_time = time.time()
print(ed_time - st_time)

0.0062915709825828725
0.0009288787841796875


In [7]:
newArr = np.array([])
newList = list()

In [8]:
%time


st_time = time.time()

for i in nparr:
    newArr = np.append(newArr, np.array(i))

ed_time = time.time()
print(ed_time - st_time)

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.25 µs
0.06801891326904297


In [9]:
st_time = time.time()

for i in pylist:
    newList.append(i)

ed_time = time.time()
print(ed_time - st_time)

0.001127004623413086


## Operator
- test
- test2

In [12]:
tmpArr = np.array([1, 2, 3, 4, 5, 6])
tmpArr

array([1, 2, 3, 4, 5, 6])

In [13]:
tmpArr > 3

array([False, False, False,  True,  True,  True])

In [14]:
tmpArr < 3

array([ True,  True, False, False, False, False])

In [15]:
tmpArr <= 3

array([ True,  True,  True, False, False, False])

In [16]:
tmpArr == 3

array([False, False,  True, False, False, False])

In [17]:
tmpArr != 3

array([ True,  True, False,  True,  True,  True])

In [18]:
tmpArr

array([1, 2, 3, 4, 5, 6])

In [19]:
(tmpArr > 2) & (tmpArr < 5)

array([False, False,  True,  True, False, False])

In [20]:
(tmpArr > 2) | (tmpArr < 5)

array([ True,  True,  True,  True,  True,  True])

In [21]:
(tmpArr > 2)

array([False, False,  True,  True,  True,  True])

In [22]:
(tmpArr < 5)

array([ True,  True,  True,  True, False, False])

In [23]:
(tmpArr > 2) ^ (tmpArr < 5)

array([ True,  True, False, False,  True,  True])